// Booking
export const UPDATE_SELECTED_SALON_ID = "UPDATE_SELECTED_SALON_ID";
export const UPDATE_SELECTED_SERVICE_ID = "UPDATE_SELECTED_SERVICE_ID";
export const UPDATE_SELECTED_STAFF_ID = "UPDATE_SELECTED_STAFF_ID";
export const UPDATE_SELECTED_DATE = "UPDATE_SELECTED_DATE";
export const UPDATE_CUSTOMER_INFO = "UPDATE_CUSTOMER_INFO";

// Get salon list
export const GET_SALON_LIST_SUCCESSFULLY = "GET_SALON_LIST_SUCCESSFULLY";
export const GET_SALON_LIST_FAILED = "GET_SALON_LIST_FAILED";
export const RESET_SALON_LIST = "RESET_SALON_LIST";

// Get service list
export const GET_SERVICE_LIST_SUCCESSFULLY = "GET_SERVICE_LIST_SUCCESSFULLY";
export const GET_SERVICE_LIST_FAILED = "GET_SERVICE_LIST_FAILED";
export const RESET_SERVICE_LIST = "RESET_SERVICE_LIST";

// Get staff list
export const GET_STAFF_LIST_SUCCESSFULLY = "GET_STAFF_LIST_SUCCESSFULLY";
export const GET_STAFF_LIST_FAILED = "GET_STAFF_LIST_FAILED";
export const RESET_STAFF_LIST = "RESET_STAFF_LIST";
