// Booking
export const UPDATE_SELECTED_SALON_ID = "UPDATE_SELECTED_SALON_ID";
export const UPDATE_SELECTED_SERVICE = "UPDATE_SELECTED_SERVICE";
export const UPDATE_SELECTED_STAFF_ID = "UPDATE_SELECTED_STAFF_ID";
export const UPDATE_SELECTED_DATE = "UPDATE_SELECTED_DATE";
export const UPDATE_CUSTOMER_INFO = "UPDATE_CUSTOMER_INFO";

export const BOOK_SERVICE_SUCCESSFULLY = "BOOK_SERVICE_SUCCESSFULLY";
export const BOOK_SERVICE_FAILED = "BOOK_SERVICE_FAILED";
export const RESET_BOOKING_DETAILS = "RESET_BOOKING_DETAILS";

// Get salon list
export const GET_SALON_LIST_SUCCESSFULLY = "GET_SALON_LIST_SUCCESSFULLY";
export const GET_SALON_LIST_FAILED = "GET_SALON_LIST_FAILED";
export const RESET_SALON_LIST = "RESET_SALON_LIST";

// Get service list
export const GET_SERVICE_LIST_SUCCESSFULLY = "GET_SERVICE_LIST_SUCCESSFULLY";
export const GET_SERVICE_LIST_FAILED = "GET_SERVICE_LIST_FAILED";
export const RESET_SERVICE_LIST = "RESET_SERVICE_LIST";

// Get salon info
export const GET_SALON_INFO_SUCCESSFULLY = "GET_SALON_INFO_SUCCESSFULLY";
export const GET_SALON_INFO_FAILED = "GET_SALON_INFO_FAILED";
export const RESET_GET_SALON_INFO = "RESET_GET_SALON_INFO";

// Get staff list
export const GET_STAFF_LIST_SUCCESSFULLY = "GET_STAFF_LIST_SUCCESSFULLY";
export const GET_STAFF_LIST_FAILED = "GET_STAFF_LIST_FAILED";
export const RESET_STAFF_LIST = "RESET_STAFF_LIST";

// Get staff free calendar
export const GET_STAFF_CALENDAR_SUCCESSFULLY = "GET_STAFF_CALENDAR_SUCCESSFULLY";
export const GET_STAFF_CALENDAR_FAILED = "GET_STAFF_CALENDAR_FAILED";
export const RESET_STAFF_CALENDAR = "RESET_STAFF_CALENDAR";

// Get history booking
export const GET_HISTORY_BOOKING_SUCCESSFULLY = "GET_HISTORY_BOOKING_SUCCESSFULLY";
export const GET_HISTORY_BOOKING_FAILED = "GET_HISTORY_BOOKING_FAILED";

// Get reservation
export const GET_RESERVATION_SUCCESSFULLY = "GET_RESERVATION_SUCCESSFULLY";
export const GET_RESERVATION_FAILED = "GET_RESERVATION_FAILED";
export const RESET_RESERVATION_LIST = "RESET_RESERVATION_LIST";

// Cancel reservation
export const CANCEL_RESERVATION_FAILED = "CANCEL_RESERVATION_FAILED";
