//GET SALON ACTIVE
export const GET_LIST_SALON_ACTIVE_SUCCESSFULLY =
  "GET_SALON_ACTIVE_SUCCESSFULLY";
export const GET_LIST_SALON_ACTIVE_FAILED = "GET_LIST_SALON_ACTIVE_FAILED";
export const RESET_LIST_SALON_ACTIVE = "RESET_LIST_SALON_ACTIVE";


// GET SALON DEACTIVE
export const GET_LIST_SALON_DEACTIVE_SUCCESSFULLY =
  "GET_LIST_SALON_DEACTIVE_SUCCESSFULLY";
export const GET_LIST_SALON_DEACTIVE_FAILED = "GET_LIST_SALON_DEACTIVE_FAILED";
export const RESET_LIST_SALON_DEACTIVE = "RESET_LIST_SALON_DEACTIVE";

// GET SALON REQUEST
export const GET_LIST_SALON_REQUEST_SUCCESSFULLY =
  "GET_LIST_SALON_REQUEST_SUCCESSFULLY";
export const GET_LIST_SALON_REQUEST_FAILED = "GET_LIST_SALON_REQUEST_FAILED";
export const RESET_LIST_SALON_REQUEST = "RESET_LIST_SALON_REQUEST";