//GET SALON ACTIVE
export const GET_LIST_SALON_ACTIVE_SUCCESSFULLY =
  "GET_SALON_ACTIVE_SUCCESSFULLY";
export const GET_LIST_SALON_ACTIVE_FAILED = "GET_LIST_SALON_ACTIVE_FAILED";
export const RESET_LIST_SALON_ACTIVE = "RESET_LIST_SALON_ACTIVE";
