//GET SALON ACTIVE
export const GET_LIST_SALON_ACTIVE_SUCCESSFULLY =
  "GET_SALON_ACTIVE_SUCCESSFULLY";
export const GET_LIST_SALON_ACTIVE_FAILED = "GET_LIST_SALON_ACTIVE_FAILED";
export const RESET_LIST_SALON_ACTIVE = "RESET_LIST_SALON_ACTIVE";

// GET SALON DEACTIVE
export const GET_LIST_SALON_DEACTIVE_SUCCESSFULLY =
  "GET_LIST_SALON_DEACTIVE_SUCCESSFULLY";
export const GET_LIST_SALON_DEACTIVE_FAILED = "GET_LIST_SALON_DEACTIVE_FAILED";
export const RESET_LIST_SALON_DEACTIVE = "RESET_LIST_SALON_DEACTIVE";

// GET SALON REQUEST
export const GET_LIST_SALON_REQUEST_SUCCESSFULLY =
  "GET_LIST_SALON_REQUEST_SUCCESSFULLY";
export const GET_LIST_SALON_REQUEST_FAILED = "GET_LIST_SALON_REQUEST_FAILED";
export const RESET_LIST_SALON_REQUEST = "RESET_LIST_SALON_REQUEST";

//UPDATE SELECTED SALON BUSINESSINFO
export const UPDATE_SELECTED_SALON_ACTIVE_BUSINESS_INFO_SUCCESFULLY =
  "UPDATE_SELECTED_SALON_ACTIVE_BUSINESS_INFO_SUCCESFULLY";
export const UPDATE_SELECTED_SALON_DEACTIVE_BUSINESS_INFO_SUCCESFULLY =
  "UPDATE_SELECTED_SALON_DEACTIVE_BUSINESS_INFO_SUCCESFULLY";
export const UPDATE_SELECTED_SALON_REQUEST_BUSINESS_INFO_SUCCESFULLY =
  "UPDATE_SELECTED_SALON_REQUEST_BUSINESS_INFO_SUCCESFULLY";

// ACTIVE SALON
export const ACTIVE_SALON_SUCCESSFULLY = "ACTIVE_SALON_SUCCESSFULLY";
export const ACTIVE_SALON_FAILED = "ACTIVE_SALON_FAILED";

//DEACTIVE SALON
export const DEACTIVE_SALON_SUCCESSFULLY = "DEACTIVE_SALON_SUCCESSFULLY";
export const DEACTIVE_SALON_FAILED = "DEACTIVE_SALON_FAILED";

//REJECT SALON
export const REJECT_SALON_SUCCESSFULLY = "REJECT_SALON_SUCCESSFULLY";
export const REJECT_SALON_FAILED = "REJECT_SALON_FAILED";

//GET SALON INFO
export const GET_SALON_INFO_FOR_ADMIN_SUCCESSFULLY =
  "GET_SALON_INFO_FOR_ADMIN_SUCCESSFULLY";
export const GET_SALON_INFO_FOR_ADMIN_FAILED =
  "GET_SALON_INFO_FOR_ADMIN_FAILED";
  export const RESET_SALON_INFO_FOR_ADMIN="RESET_SALON_INFO_FOR_ADMIN"

//GET SALON REVIEW
export const GET_REVIEW_FOR_ADMIN_SUCCESSFULLY =
  "GET_REVIEW_FOR_ADMIN_SUCCESSFULLY";
export const GET_REVIEW_FOR_ADMIN_FAILED = "GET_REVIEW_FOR_ADMIN_FAILED";
export const RESET_REVIEW_SALON_FOR_ADMIN="RESET_REVIEW_SALON_FOR_ADMIN"
