//GET REVIEW FOR CUSTOMER
export const GET_REVIEW_FOR_CUSTOMER_SUCCESSFULLY =
  "GET_REVIEW_FOR_CUSTOMER_SUCCESSFULLY";
export const GET_REVIEW_FOR_CUSTOMER_FAILED = "GET_REVIEW_FOR_CUSTOMER_FAILED";
export const RESET_LIST_REVIEW_FOR_CUSTOMER = "RESET_LIST_REVIEW_FOR_CUSTOMER";

//ADD REVIEW FOR CUSTOMER
export const ADD_REVIEW_FOR_CUSTOMER_SUCCESSFULLY =
  "ADD_REVIEW_FOR_CUSTOMER_SUCCESSFULLY";
export const ADD_REVIEW_FOR_CUSTOMER_FAILED = "ADD_REVIEW_FOR_CUSTOMER_FAILED";

//GET REVIEW FOR SALON
export const GET_REVIEW_FOR_SALON_SUCCESSFULLY =
  "GET_REVIEW_FOR_SALON_SUCCESSFULLY";
export const GET_REVIEW_FOR_SALON_FAILED = "GET_REVIEW_FOR_SALON_FAILED";
export const RESET_LIST_REVIEW_FOR_SALON = "RESET_LIST_REVIEW_FOR_SALON";

//EDIT REVIEW FOR CUSTOMER
export const EDIT_REVIEW_FOR_CUSTOMER_SUCCESSFULLY =
  "EDIT_REVIEW_FOR_CUSTOMER_SUCCESSFULLY";
export const EDIT_REVIEW_FOR_CUSTOMER_FAILED =
  "EDIT_REVIEW_FOR_CUSTOMER_FAILED";

//DELETE REVIEW FOR CUSTOMER
export const DELETE_REVIEW_FOR_CUSTOMER_SUCCESSFULLY =
  "DELETE_REVIEW_FOR_CUSTOMER_SUCCESSFULLY";
export const DELETE_REVIEW_FOR_CUSTOMER_FAILED =
  "DELETE_REVIEW_FOR_CUSTOMER_FAILED";
