//Get profile salon for Salon owner
export const GET_PROFILE_FOR_SALON_SUCCESSFULLY =
  "GET_PROFILE_FOR_SALON_SUCCESSFULLY";
export const GET_PROFILE_FOR_SALON_FAILED = "GET_PROFILE_FOR_SALON_FAILED";

//Get Schedule
export const GET_SCHEDULE_CURRENT_SUCCESSFULLY =
  "GET_SCHEDULE_CURRENT_SUCCESSFULLY";
export const GET_SCHEDULE_CURRENT_FAILED = "GET_SCHEDULE_CURRENT_FAILED";
export const RESET_SCHEDULE_CURRENT_LIST = "RESET_SCHEDULE_CURRENT_LIST";

//get history booking service
export const GET_HISTORY_BOOKING_SUCCESSFULLY =
  "GET_HISTORY_BOOKING_SUCCESSFULLY";
export const GET_HISTORY_BOOKING_FAILED = "GET_HISTORY_BOOKING_FAILED";
export const RESET_HISTORY_BOOKING_LIST = "RESET_HISTORY_BOOKING_LIST";

//finish order
export const FINISH_ORDER_SUCCESSFULLY = "FINISH_ORDER_SUCCESSFULLY";
export const FINISH_ORDER_FAILED = "FINISH_ORDER_SUCCESSFULLY";

//cancel order
export const CANCEL_ORDER_SUCCESSFULLY = "CANCEL_ORDER_SUCCESSFULLY";
export const CANCEL_ORDER_FAILED = "CANCEL_ORDER_FAILED";

//get staff of salon
export const GET_STAFF_LIST_FOR_SALON_SUCCESSFULLY =
  "GET_STAFF_LIST_FOR_SALON_SUCCESSFULLY";
export const GET_STAFF_LIST_FOR_SALON_FAILED =
  "GET_STAFF_LIST_FOR_SALON_FAILED";
export const RESET_STAFF_LIST_OF_SALON = "RESET_STAFF_LIST_OF_SALON";

//get service list of salon
export const GET_SERVICE_LIST_FOR_SALON_SUCCESSFULLY =
  "GET_SERVICE_LIST_FOR_SALON_SUCCESSFULLY";
export const GET_SERVICE_LIST_FOR_SALON_FAILED =
  "GET_SERVICE_LIST_FOR_SALON_FAILED";
export const RESET_SERVICE_LIST_OF_SALON = "RESET_SERVICE_LIST_OF_SALON";

//add new service for salon
export const ADD_NEW_SERVICE_SUCCESSFULLY="ADD_NEW_SERVICE_SUCCESSFULLY"
export const ADD_NEW_SERVICE_FAILED="ADD_NEW_SERVICE_SUCCESSFULLY"

//EDIT SERVICE
export const EDIT_SERVICE_SUCCESSFULLY="EDIT_SERVICE_SUCCESSFULLY"
export const EDIT_SERVICE_FAILED="EDIT_SERVICE_FAILED"

//DELETE SERVICE
export const DELETE_SERVICE_SUCCESSFULLY="DELETE_SERVICE_SUCCESSFULLY"
export const DELETE_SERVICE_FAILED="DELETE_SERVICE_FAILED"

//add new staff for salon
export const ADD_NEW_STAFF_SUCCESSFULLY="ADD_NEW_STAFF_SUCCESSFULLY"
export const ADD_NEW_STAFF_FAILED="ADD_NEW_STAFF_FAILED"


//EDIT PROFILE FOR SALON
export const UPDATE_SALON_PROFILE_SUCCESSFULLY="UPDATE_SALON_PROFILE_SUCCESSFULLY"
export const UPDATE_SALON_PROFILE_FAILED="UPDATE_SALON_PROFILE_FAILED"

//EDIT STAFF
export const EDIT_STAFF_INFO_SUCCESSFULLY="EDIT_STAFF_INFO_SUCCESSFULLY"
export const EDIT_STAFF_INFO_FAILED="EDIT_STAFF_INFO_FAILED"

//DELETE STAFF
export const DELETE_STAFF_SUCCESSFULLY="DELETE_STAFF_SUCCESSFULLY"
export const DELETE_STAFF_FAILED="DELETE_STAFF_FAILED"

//EDIT SALON BUSINESS INFO
export const EDIT_SALON_BUSINESS_INFO_SUCCESSFULLY="EDIT_SALON_BUSINESS_INFO_SUCCESSFULLY"
export const EDIT_SALON_BUSINESS_INFO_FAILED="EDIT_SALON_BUSINESS_INFO_FAILED"

//EDIT SALON  INFO
export const EDIT_SALON_INFO_SUCCESSFULLY="EDIT_SALON_INFO_SUCCESSFULLY"
export const EDIT_SALON_INFO_FAILED="EDIT_SALON_INFO_FAILED"