// Get customer profile
export const GET_CUSTOMER_PROFILE_SUCCESSFULLY =
  "GET_CUSTOMER_PROFILE_SUCCESSFULLY";
export const GET_CUSTOMER_PROFILE_FAILED = "GET_CUSTOMER_PROFILE_FAILED";
export const UPDATE_CUSTOMER_PROFILE_SUCCESSFULLY =
  "UPDATE_CUSTOMER_PROFILE_SUCCESSFULLY";
export const UPDATE_CUSTOMER_PROFILE_FAILED = "UPDATE_CUSOTOMER_PROFILE_FAILED";
export const CLEAR_CUSTOMER_PROFILE_MESSAGE = "CLEAR_CUSTOMER_PROFILE_MESSAGE";
