//Login
export const LOGIN_SUCCESSFULLY = "LOGIN_SUCCESSFULLY";
export const LOGIN_FAILED = "LOGIN_FAILED";

//Logout
export const LOGOUT_SUCCESSFULLY = "LOGOUT_SUCCESSFULLY";
export const LOGOUT_FAILED = "LOGOUT_FAILED";

//Đăng ký
export const SIGN_UP_SUCCESSFULLY = "SIGN_UP_SUCCESSFULLY";
export const SIGN_UP_FAILED = "SIGN_UP_FAILED";

//Quên mật khẩu
export const RECOVER_PASSWORD_SUCCESSFULLY="RECOVER_PASSWORD_SUCCESSFULLY";
export const RECOVER_PASSWORD_FAILED="RECOVER_PASSWORD_FAILED";


